### ISSUE TITLE
undefined method `cashier'

### ISSUE THREAD

**Issue by mixellent** [ahawkins/cashier#6]
Trying to use this cool gem, but I am struggling starting my application with it (am I missing something simple here?).
I added the cashier gem to my Gemfile and I also added the following to my development.rb file: 

```
config.cashier.adapter.redis = REDIS_OBJ_HERE
```

I am getting the following error when running my rails server:

```
undefined method `cashier' for #<Rails::Application::Configuration:0x007fdfd11bdc18>
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/railtie/configuration.rb:85:in `method_missing'
/Users/michael/Projects/mixellent/config/environments/development.rb:58:in `block in <top (required)>'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:24:in `class_eval'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:24:in `configure'
/Users/michael/Projects/mixellent/config/environments/development.rb:1:in `<top (required)>'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `block in require'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/engine.rb:571:in `block in <class:Engine>'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `run'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `each'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/application.rb:136:in `initialize!'
/Users/michael/.rvm/gems/ruby-1.9.3-p0@rails326/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/michael/Projects/mixellent/config/environment.rb:5:in `<top (required)>'
```

Note: I am using Rails 3.2.6 on Ruby 1.9.3.

Thanks,

Michael

**Comment by assembler** [comment]
+1

**Comment by assembler** [comment]
I ended up adding this into development.rb file:

``` ruby
config.cashier = Cashier
config.cashier.adapter = :redis_store
config.cashier.adapter.redis = REDIS_OBJ_HERE
```

**Comment by ScotterC** [comment]
+1 here too.  Thanks @assembler for the code

**Comment by lukes** [comment]
@assembler I ended up adding similar code to an initializer:

```
Cashier.adapter = :redis_store
Cashier.adapter.redis = REDIS_OBJ_HERE # or in my case, Resque.redis
```

**Comment by ahawkins** [comment]
@mixellent  @assembler  Fixed in 0.4.1. I just released it. Does this fix your issue?
